version: '3'

services:
  postgresql:
    container_name : postgresql11
    image: postgres
    ports:
      - '5432:5432'
    environment:
#      - POSTGRESQL_USERNAME=testabc
      - POSTGRESQL_PASSWORD=postgres
#      - POSTGRESQL_DATABASE=my_database
    privileged: true
#    volumes:
#      - ./postgresql_data:/bitnami/postgresql
#      - ./postgresql_conf:/opt/bitnami/postgresql/conf/