version: '3'

services:
  postgresql:
    container_name : postgres_11
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=my_database
