spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      scheduler:
        instanceName : SchuduleClusteredScheduler
        instanceId : AUTO
      threadPool:
        class : org.quartz.simpl.SimpleThreadPool
        threadCount : 25
        threadPriority : 5
      jobStore:
        misfireThreshold : 5000
        class : org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass : org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        useProperties : false
        dataSource : scheduleDS
        tablePrefix : QRTZ_
        isClustered : true
        clusterCheckinInterval : 20000
      dataSource:
        scheduleDS:
          driver : org.postgresql.Driver
          URL : jdbc:postgresql://localhost:5432/mps_lot
          user : mps_lot
          password : mps_lot123
          maxConnections : 5
          validationQuery : select 1